### ISSUE TITLE
OnCreate presenter object is null

### ISSUE THREAD

**Issue by kazimdsaidul** [BrianEstrada/Android-MVP-Boilerplate#1]
![unnamed](https://user-images.githubusercontent.com/909987/29876667-be467e22-8d9d-11e7-8c2a-76110caa7137.png)

OnCreate presenter object is null

**Comment by BrianEstrada** [comment]
![screen shot 2017-08-30 at 4 09 25 pm](https://user-images.githubusercontent.com/909987/29876693-c8c54220-8d9d-11e7-9951-d93c5900439d.png)

The presenter isn't available until after onStart so try calling it from that and see if you still get that error
